Feat/modelhub (#1) (#2)
* feat: translations (#3176)

* fix: prompt editor variable picker (#3177)

* Fix: features of agent-chat (#3178)

* version to 0.6.0-fix1 (#3179)

* fix keyword index error when storage source is S3 (#3182)

* Update README.md to include workflows (#3180)

* Compatible with unique index conflicts (#3183)

* fix: sometimes chosed old selected knowledge may overwirte the new knowledge (#3199)

* Fix: remove unavailable return_preamble parameter in cohere (#3201)



* Fix/code transform result (#3203)

* fix(code_executor): surrogates not allowed error in jinja2 template (#3191)

* fix: node connect self (#3194)

* Update README.md (#3206)

* fix economy index search in workflow (#3205)

* fix: index number in api/README (#3214)

* Update README.md (#3212)

* fix detached instance error in keyword index create thread and fix question classifier node out of index error (#3219)

* fix: incomplete response (#3215)

* fix: latest image tag not push in GitHub action (#3213)

* fix: vision config doesn't enabled in llm (#3225)

* fixed the issue of missing cleanup function in the AudioBtn component (#3133)

* fix: image text when retrieve chat histories (#3220)

* feat: moonshot function call (#3227)

* feat: support setting database used in Milvus (#3003)

* fix milvus database name parameter missed (#3229)

* fix: file not uploaded caused api error (#3228)

* update link (#3226)

* fix: skip Celery warning by setting broker_connection_retry_on_startup config (#3188)

* fix: workflow run edge status (#3236)

* fix: empty conversation list of explore chatbot (#3235)

* Fix: picture of workflow (#3241)

* feat: prompt-editor support undo (#3242)

* fix: number type in app would render as select type in webapp (#3244)

* fix: token is not logging of question classifier node (#3249)

* chore: remove langchain in tools (#3247)

* make sure validation flow works for all model providers in bedrock (#3250)

* feat: remove unregistered-llm-in-debug (#3251)

* version to 0.6.1 (#3253)

* fix: agent chat multiple model debug (#3258)

* feat: gpt-4-turbo (#3263)

* fix: image was sent to an unsupported LLM when sending second message (#3268)

* feat: vision parameter support of OpenAI Compatible API (#3272)

* fix: var assigner input node can not find caused error (#3274)

* fix: variable-assigner node connect (#3288)

* Feat/Agent-Image-Processing (#3293)



* chore: address security alerts on braces escape and KaTeX (#3301)

* chore(deps): bump katex from 0.16.8 to 0.16.10 in /web (#3307)




* Update README.md (#3281)

* Remove langchain dataset retrival agent logic (#3311)

* add german translations (#3322)

* feat: add missing workflow i18n keys (#3309)



* feat:add 'name' field return (#3152)

* improvement: speed up dependency installation in docker image rebuilds by mounting cache layer (#3218)

* feat: support gpt-4-turbo-2024-04-09 model (#3300)

* feat: Add Cohere Command R / R+ model support (#3333)

* fix dataset retrival in dataset mode (#3334)

* chore:bump pypdfium2 from 4.16.0 to 4.17.0 (#3310)

* feat(llm/models): add gemini-1.5-pro (#2925)

* feat: make input size bigger in start (#3340)

* Doc/update readme (#3344)

* fix: leave  progress page still call indexing-status api (#3345)

* feat: update aws bedrock (#3326)



* fix/moonshot-function-call (#3339)

* fix issue: user’s keywords do not affect when add segment (#3349)

* add segment with keyword issue (#3351)



* Fix issue : don't delete DatasetProcessRule, DatasetQuery and AppDatasetJoin when delete dataset with no document (#3354)

* fix: remove middle editor may cause render placement error (#3356)

* Added a note on the front-end docker build: use taobao source to accelerate the installation of front-end dependency packages to achieve the purpose of quickly building containers (#3358)




* fix: var name too long would break ui in var assigner and end nodes (#3361)

* Refactor/react agent (#3355)

* Fix/Bing Search url endpoint cannot be customized (#3366)

* fix: image token calc of OpenAI Compatible API (#3368)

* Update README.md (#3371)

* update workflow intro mp4 codec (#3372)

* fix: cohere tool call does not support single tool (#3373)

* version to 0.6.2 (#3375)

* fix: variable pool mapping variable mixed up (#3378)

* version to 0.6.2-fix1 (#3380)

* fix: yarn install extract package err when using GitHub Cache in amd6… (#3383)

* feat: Add support for embed file with AWS Bedrock Titan Model (#3377)



* fix: remove - in dataset retriever tool name (#3381)

* feat:api Add support for extracting EPUB files in ExtractProcessor (#3254)



* feat: show citation info in run history (#3399)

* Feat: Invitation link automatically completes domain name (#3393)



* Integrated SearXNG search as built-in tool (#3363)



* fix: [azure_openai] Error: 'NoneType' object has no attribute 'content' (#3389)

* Update providers preview (#3403)

* add xls file suport (#3321)

* Update README.md (#3405)

* Fix/workflow tool incorrect parameter configurations (#3402)



* chore: replace all set interval (#3411)

* feat: Deprecate datetime.utcnow() in favor of datetime.now(timezone.utc).replace(tzinfo=None) for better timezone handling (#3408) (#3416)

* chore: remove Langchain tools import (#3407)

* feat: gemini pro function call (#3406)

* fix: shared text-generation stream (#3419)

* fix/dataset-retriever-tool-parameter-redundancy (#3418)

* Feat/api tool custom timeout (#3420)

* fix: test env key missing or wrong (#3430)

* Doc/update readme (#3433)

* Update README_CN.md (#3434)

* Update README_CN.md (#3435)

* feat: add workflow editor shortcuts (#3382) (#3390)

* FEAT: cohere rerank 3 model added (#3431)

* chore: remove the COPY instruction in .devcontainer/Dockerfile (#3409)

* fix typo: Changlog -> Changelog (#3442)

* fix: node shortcuts active in input fields (#3438)

* Add nvidia codegemma 7b (#3437)

* Update yaml and py file in Tavily Tool (#3450)

* feat: Added the mirror of Aliyun's Linux apk installation package and updated the deprecated taobao npm mirror address to npmmirror (#3459)

* Revert "Update yaml and py file in Tavily Tool" (#3464)

* feat: jina reader (#3468)

* feat: support configurate openai compatible stream tool call (#3467)

* feat: optimize the efficiency of generating chatbot conversation name (#3472)

* feat: remove langchain from output parsers (#3473)

* chore: separate Python dependencies for development (#3198)

* chore: add sandbox permission tooltip (#3477)

* fix: prompt template issue (#3449)

* feat: support relyt vector database  (#3367)



* Update README.md (#3478)

* nvidia-label-update (#3482)

* fix: in conversation log click op button would cause close drawer (#3483)

* fix: workflow auto layout nodes offset & delete node shortcuts (#3484)

* fix: workflow edge curvature (#3488)

* fix: stringify object while exporting batch result to csv (#3481)

* question classifier prompt optimization (#3479)

* feat: refactor tongyi models (#3496)

* fix: bump twilio to 9.0.4 skipping yanked versions (#3500)

* test: install ffmpeg for pytests (#3499)

* feat: support var auto rename in prompt editor (#3510)

* fix: add message caused problem after simple chat convert to workflow (#3511)

* fix: the object field is empty string in some openAI api compatible model (#3506)

* Add suuport for AWS  Bedrock Cohere embedding (#3444)

* fix: add completion mode object check (#3515)

* get config default for sandbox (#3508)



* chore: improve reference variable picker user experience (#3517)

* fix: array[string] context in llm node invalid (#3518)

* version to 0.6.3 (#3519)

* fix the return with wrong datatype of segment (#3525)

* fix: the hover style of the card-item operation button container (#3520)

* chore: lint .env file templates (#3507)

* add support for swagger object type (#3426)



* /fix register

* /add modelhub

* localhost

* /fix req bugs

* modelhub add rerank

---------

Signed-off-by: Jat <jat@sinosky.org>
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: crazywoola <100913391+crazywoola@users.noreply.github.com>
Co-authored-by: zxhlyh <jasonapring2015@outlook.com>
Co-authored-by: KVOJJJin <jzongcode@gmail.com>
Co-authored-by: takatost <takatost@users.noreply.github.com>
Co-authored-by: Jyong <76649700+JohnJyong@users.noreply.github.com>
Co-authored-by: Chenhe Gu <guchenhe@gmail.com>
Co-authored-by: Joel <iamjoel007@gmail.com>
Co-authored-by: Jat <jat@sinosky.org>
Co-authored-by: Yeuoly <45712896+Yeuoly@users.noreply.github.com>
Co-authored-by: Eric Wang <wrqatw@gmail.com>
Co-authored-by: Bowen Liang <liangbowen@gf.com.cn>
Co-authored-by: legao <837937787@qq.com>
Co-authored-by: Leo Q <LeoQuote@users.noreply.github.com>
Co-authored-by: minakokojima <lychees67@gmail.com>
Co-authored-by: Nite Knite <nkCoding@gmail.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Lao <khazzz1c@gmail.com>
Co-authored-by: lbm21 <313338264@qq.com>
Co-authored-by: 呆萌闷油瓶 <253605712@qq.com>
Co-authored-by: Kenny <kt.tian@gmail.com>
Co-authored-by: akou <beiming1201@gmail.com>
Co-authored-by: longzhihun <38651850@qq.com>
Co-authored-by: LiuVaayne <10231735+vaayne@users.noreply.github.com>
Co-authored-by: crazywoola <427733928@qq.com>
Co-authored-by: Moonlit <bc.h@foxmail.com>
Co-authored-by: huangbaichao <hbc@moonlit.art>
Co-authored-by: junytang <junytang@gmail.com>
Co-authored-by: saga.rey <saga.rey@outlook.com>
Co-authored-by: chenxu9741 <1309095142@qq.com>
Co-authored-by: LIU HONGWEI <1327374483@qq.com>
Co-authored-by: Pascal M <11357019+perzeuss@users.noreply.github.com>
Co-authored-by: Yash Parmar <82636823+Yash-1511@users.noreply.github.com>
Co-authored-by: Bodhi <3882561+BodhiHu@users.noreply.github.com>
Co-authored-by: Selene29 <funmailfach@web.de>
Co-authored-by: Josh Feng <noisywolf@gmail.com>
Co-authored-by: Richards Tu <142148415+richards199999@users.noreply.github.com>
Co-authored-by: YidaHu <huyidada@gmail.com>
Co-authored-by: Jingpan Xiong <71321890+klaus-xiong@users.noreply.github.com>
Co-authored-by: jingsi <jingsi@leadincloud.com>
Co-authored-by: Joshua <138381132+joshua20231026@users.noreply.github.com>
Co-authored-by: sino <sino2322@gmail.com>
Co-authored-by: liuzhenghua <1090179900@qq.com>
Co-authored-by: kerlion <40377268+kerlion@users.noreply.github.com>
Co-authored-by: miendinh <22139872+miendinh@users.noreply.github.com>
Co-authored-by: miendinh <miendinh@users.noreply.github.com>
Co-authored-by: buu <bushuai@yahoo.com>
Co-authored-by: LeePui <444561897@qq.com>
Co-authored-by: lipeikui <lipeikui@3vjia.com>